<?php
/**
 * Created by PhpStorm.
 * User: lhwa-seon
 * Date: 19/10/2018
 * Time: 16:29
 */

namespace App\DecoratorEtude;

class PlainTextFilter extends TextFormat
{
    public function formatText(string $text): string
    {
        $text = parent::formatText($text); // TODO: Change the autogenerated stub
        return strip_tags($text);
    }
}
